name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: rust-toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        # Rust toolchain name
        toolchain: nightly
        # Target triple to install for this toolchain
        target: wasm32-unknown-unknown
    - name: Cache
      uses: actions/cache@v2.1.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose --release --target wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --verbose
